# Generated by Django 6.0 on 2026-04-08 15:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Draw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("draw_date", models.DateField()),
                ("draw_number", models.PositiveSmallIntegerField()),
                ("result_text", models.TextField(blank=True)),
                (
                    "winnings_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_current", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-draw_date", "-draw_number"],
            },
        ),
        migrations.CreateModel(
            name="DrawComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "draw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="lotto.draw",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DrawImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="draw_images/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                (
                    "draw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="lotto.draw",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MonthlySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.PositiveSmallIntegerField()),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "total_winnings",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-year", "-month"],
                "unique_together": {("month", "year")},
            },
        ),
        migrations.AddField(
            model_name="draw",
            name="monthly_summary",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="draws",
                to="lotto.monthlysummary",
            ),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("draws_paid_for", models.PositiveSmallIntegerField(default=4)),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("joined_at", models.DateField(default=django.utils.timezone.now)),
                ("expiry_date", models.DateField()),
                ("active", models.BooleanField(default=True)),
                (
                    "monthly_summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="lotto.monthlysummary",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-joined_at"],
                "unique_together": {("user", "monthly_summary")},
            },
        ),
    ]
