# Generated by Django 6.0 on 2026-04-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draw',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Only one draw should be marked as current at a time.'),
        ),
    ]
