# Generated by Django 6.0 on 2026-04-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0003_monthlysummary_subscription_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
